# Generated by Django 5.2.11 on 2026-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_t_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('x', 'player 1'), ('o', 'player 2'), ('empty', 'non played')], default='empty', help_text='Winner of the game', max_length=5),
        ),
        migrations.AlterField(
            model_name='box',
            name='piece',
            field=models.CharField(choices=[('x', 'player 1'), ('o', 'player 2'), ('empty', 'non played')], default='empty', help_text='Pieces per box', max_length=255),
        ),
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='board',
            name='position',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('i', 'in progress'), ('f', 'finished'), ('n', 'not started')], default='n', help_text='Game Status', max_length=1),
        ),
        migrations.AddField(
            model_name='box',
            name='position',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('i', 'in progress'), ('f', 'finished'), ('n', 'not started')], default='n', help_text='Game Status', max_length=1),
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
