# Generated by Django 5.2.11 on 2026-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_t_app', '0002_alter_game_winner_alter_box_piece_remove_game_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in progress'), ('Finished', 'finished'), ('Not started', 'not started')], default='n', help_text='Game Status', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in progress'), ('Finished', 'finished'), ('Not started', 'not started')], default='n', help_text='Game Status', max_length=255),
        ),
    ]
