# Generated by Django 5.2.11 on 2026-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_t_app', '0003_alter_board_status_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('In Progress', 'in progress'), ('Finished', 'finished'), ('Not started', 'not started')], default='Not started', help_text='Game Status', max_length=255),
        ),
    ]
