# Generated by Django 5.2.11 on 2026-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_t_app', '0004_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('Not started', 'not started'), ('In Progress', 'in progress'), ('Finished', 'finished')], default='n', help_text='Game Status', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Not started', 'not started'), ('In Progress', 'in progress'), ('Finished', 'finished')], default='Not started', help_text='Game Status', max_length=255),
        ),
    ]
