# Generated by Django 5.2.11 on 2026-02-19 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_t_app', '0005_alter_board_status_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_t_app.game'),
        ),
        migrations.AlterField(
            model_name='box',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_t_app.board'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
